services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ame
      POSTGRES_PASSWORD: ame1234
      POSTGRES_DB: products_amazon
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: products_amazon
      DB_USER: ame
      DB_PASS: ame1234
    volumes:
      - .:/trab1

volumes:
  postgres_data: